blueprint:
  name: TV Samsung Turn On (forced)
  description: >
    Включает телевизор Samsung с помощью remote.turn_on несколько раз 
    после нахождения в состоянии off в течение указанного времени.
    Работает по будням в рабочее время.

  domain: automation
  input:
    tv_entity:
      name: TV media player
      description: Медиа-сущность телевизора (например, media_player.samsung_tv)
      selector:
        entity:
          domain: media_player
    remote_entity:
      name: Remote entity
      description: Remote-сущность (например, remote.samsung_tv)
      selector:
        entity:
          domain: remote
    delay_seconds:
      name: Off duration before attempting turn on (seconds)
      default: 15
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: seconds
    repeat_count:
      name: Number of turn on attempts
      default: 3
      selector:
        number:
          min: 2
          max: 5
    repeat_delay:
      name: Delay between attempts (seconds)
      default: 5
      selector:
        number:
          min: 3
          max: 10
          unit_of_measurement: seconds

trigger:
  - platform: state
    entity_id: !input tv_entity
    to: "off"
    for:
      seconds: !input delay_seconds

condition:
  - condition: time
    after: "10:00:00"
    before: "19:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri

action:
  - repeat:
      count: !input repeat_count
      sequence:
        - service: remote.turn_on
          target:
            entity_id: !input remote_entity
        - delay:
            seconds: !input repeat_delay

mode: single
